// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdTjPB_F_YoAtGl46iqi7fzMV0n7crHM',
    appId: '1:570471288708:web:e14cf3ab988fcee0a317d1',
    messagingSenderId: '570471288708',
    projectId: 'pinpoint-19',
    authDomain: 'pinpoint-19.firebaseapp.com',
    storageBucket: 'pinpoint-19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCryvyNueZE_WuljAvXr5UlVeALbTBFoS8',
    appId: '1:570471288708:android:94c94942d32581c4a317d1',
    messagingSenderId: '570471288708',
    projectId: 'pinpoint-19',
    storageBucket: 'pinpoint-19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmfhBnJJVeUUYcGN_Wz3UaMNNd0RMHxlM',
    appId: '1:570471288708:ios:0df4ee078a979dbda317d1',
    messagingSenderId: '570471288708',
    projectId: 'pinpoint-19',
    storageBucket: 'pinpoint-19.firebasestorage.app',
    iosBundleId: 'com.example.pinPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmfhBnJJVeUUYcGN_Wz3UaMNNd0RMHxlM',
    appId: '1:570471288708:ios:0df4ee078a979dbda317d1',
    messagingSenderId: '570471288708',
    projectId: 'pinpoint-19',
    storageBucket: 'pinpoint-19.firebasestorage.app',
    iosBundleId: 'com.example.pinPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIdTjPB_F_YoAtGl46iqi7fzMV0n7crHM',
    appId: '1:570471288708:web:430ffed6660214e1a317d1',
    messagingSenderId: '570471288708',
    projectId: 'pinpoint-19',
    authDomain: 'pinpoint-19.firebaseapp.com',
    storageBucket: 'pinpoint-19.firebasestorage.app',
  );
}
